server:
  servlet:
    context-path: /dirty-code

spring:
  datasource:
    url: jdbc:h2:mem:dirtycode;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DEFAULT_NULL_ORDERING=HIGH
    driverClassName: org.h2.Driver
    username: sa
    password: ""
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
  h2:
    console:
      enabled: true
      path: /h2-console
  flyway:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always

app:
  frontend:
    login-url: http://localhost:3000/api/login?token=%s&refreshToken=%s

firebase:
  enabled: false
  type: ""
  project-id: ""
  private-key-id: ""
  private-key: ""
  client-email: ""
  client-id: ""
  auth-uri: ""
  token-uri: ""
  auth-provider-x509-cert-url: ""
  client-x509-cert-url: ""
  universe-domain: ""
  api-key: ""
  auth-domain: ""
  storage-bucket: ""
  messaging-sender-id: ""
  app-id: ""
  measurement-id: ""

gcp:
  client-id: ""
  client-secret: ""
  escaped-redirect-uri: http%3A%2F%2Flocalhost%3A8080%2Fdirty-code%2Fv1%2Fgmail%2Fcall-back
  redirect-uri: "http://localhost:8080/dirty-code/v1/gmail/call-back"