server:
  servlet:
    context-path: /dirty-code

spring:
  datasource:
    url: ${DATABASE_URL}
    driver-class-name: org.postgresql.Driver
    username: ${DATABASE_USER}
    password: ${DATABASE_PASS}
    hikari:
      maximum-pool-size: 5
      minimum-idle: 1
      idle-timeout: 30000
      connection-timeout: 30000
      max-lifetime: 1800000
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    locations: classpath:db/migration

firebase:
  enabled: true
  type: ${FIREBASE_TYPE}
  project-id: ${FIREBASE_PROJECT_ID}
  private-key-id: ${FIREBASE_PRIVATE_KEY_ID}
  private-key: ${FIREBASE_PRIVATE_KEY}
  client-email: ${FIREBASE_CLIENT_EMAIL}
  client-id: ${FIREBASE_CLIENT_ID}
  auth-uri: ${FIREBASE_AUTH_URI}
  token-uri: ${FIREBASE_TOKEN_URI}
  auth-provider-x509-cert-url: ${FIREBASE_AUTH_PROVIDER_X509_CERT_URL}
  client-x509-cert-url: ${FIREBASE_CLIENT_X509_CERT_URL}
  universe-domain: ${FIREBASE_UNIVERSE_DOMAIN}

gcp:
  client-id: ${GCP_CLIENT_ID}
  client-secret: ${GCP_CLIENT_SECRET}
  escaped-redirect-uri: ${ESCAPED_REDIRECT_URL}
  redirect-uri: ${REDIRECT_URL}